### ISSUE TITLE
Public ip

### ISSUE THREAD

**Issue by dzubchik** [roquie/ansible-kontena-agent#4]
What do you think about adding automated/manual public ip?

**Comment by roquie** [comment]
What use case for this? I don't understand what for needed. Please say more about your idea.

**Comment by dzubchik** [comment]
Kontena agent has configuration option KONTENA_PUBLIC_IP. So if you want to expose load-balancer or some other public service it would be nice to have it in this role. "Automatic" means get server public IP using some service, for example: https://httpbin.org/ip, manual - user input.

**Comment by roquie** [comment]
I can to create template with env variable like as here: https://github.com/roquie/ansible-kontena-server/blob/master/templates/kontena-server.env.j2

and replace conf file like as:
https://github.com/roquie/ansible-kontena-server/blob/master/tasks/main.yml#L39

Ok?

So as this role configure only 3 variables, but kontena-agent contains has more https://kontena.io/docs/references/environment-variables.html

I think it's more usable solution that here is now.

**Comment by dzubchik** [comment]
Solution with template looks like more flexible and supportable.

**Comment by roquie** [comment]
Sure. Tonight or tomorrow night I'll create PR and leave a link here. Then, can you check script work on your system?

**Comment by roquie** [comment]
ping @dzubchik 

see PR https://github.com/roquie/ansible-kontena-agent/pull/6

**Comment by roquie** [comment]
Resolved.
