### ISSUE TITLE
Why is resolveconf installed?

### ISSUE THREAD

**Issue by dzubchik** [roquie/ansible-kontena-agent#5]
It just broke internal dns resolution.

**Comment by roquie** [comment]
I don't remember for sure, maybe this a Kontena dependency. I'll check it, when will I work on issue #4.

**Comment by roquie** [comment]
Now, resolvconf is a optional for installing https://github.com/roquie/ansible-kontena-agent/pull/7

**Comment by roquie** [comment]
Resolved.
