### ISSUE TITLE
Docker does not restart

### ISSUE THREAD

**Issue by dzubchik** [roquie/ansible-kontena-agent#9]
I do not see the reason why docker should be restarted. Moreover, always restarted.

### Expected behavior:
Docker does not restart
### Actual Behavior:
Docker does restart

**Comment by roquie** [comment]
https://github.com/kontena/kontena/blob/master/agent/packaging/ubuntu_xenial/kontena-agent/DEBIAN/postinst#L21

After install official package, docker daemon must be reloaded and restarted. I think it's worth keeping follow official script.
